components:
  schemas:

    Role:
      type: object
      required: [id, code]
      properties:
        id:
          type: string
          format: uuid
          example: 8a43f43d-65c7-4f58-8578-2ce9f85f1536
        code:
          type: string
          maxLength: 50
          example: moderator
        label:
          type: string
          nullable: true
          maxLength: 255
          example: Moderator
        is_system:
          type: boolean
          example: false
        permissions:
          type: array
          items:
            type: string
          example: [admin.users.read, admin.users.update]

    AccessPermission:
      type: object
      required: [id, code, scope]
      properties:
        id:
          type: string
          format: uuid
          example: 3f8d4f3b-7cf7-4e36-a6cf-f84e0f6f19bb
        code:
          type: string
          example: admin.users.read
        scope:
          type: string
          example: admin
        label:
          type: string
          nullable: true
          example: Просмотр пользователей в админке


    CreateRoleRequest:
      type: object
      required: [code]
      properties:
        code:
          type: string
          maxLength: 50
          example: editor
        label:
          type: string
          nullable: true
          maxLength: 255
          example: Editor
        permissions:
          type: array
          items:
            type: string
          example: [admin.users.read, admin.users.update]


    UpdateRoleRequest:
      type: object
      properties:
        code:
          type: string
          maxLength: 50
          example: editor
        label:
          type: string
          nullable: true
          maxLength: 255
          example: Updated Editor
        permissions:
          type: array
          items:
            type: string
          example: [admin.users.read]
